const data = [
    {
      "brand": "Apple",
      "model_number": "MacBook Air M1",
      "display_size": "13.3 inch",
      "ram": "8 GB",
      "rom": "256 GB SSD",
      "price_in_tk": 110000,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBa-C--IZu_NvxTyLopalZbSljZGuQVqXKtA&s",
      "color": "Silver",
      "discount": true,
      "discount_price": 99000
    },
    {
      "brand": "Apple",
      "model_number": "MacBook Pro M2",
      "display_size": "14 inch",
      "ram": "16 GB",
      "rom": "512 GB SSD",
      "price_in_tk": 180000,
      "image": "https://static.independent.co.uk/2022/06/22/11/macbook%20pro%20m2%20indybest.jpg",
      "color": "Space Gray",
      "discount": false,
      "discount_price": 180000
    },
    {
      "brand": "Apple",
      "model_number": "MacBook Pro 16",
      "display_size": "16 inch",
      "ram": "32 GB",
      "rom": "1 TB SSD",
      "price_in_tk": 250000,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI6n2BMPc0dKJbwzeKyIZZyUSBAWeFTZvkZQ&s",
      "color": "Silver",
      "discount": true,
      "discount_price": 225000
    },
    {
      "brand": "Lenovo",
      "model_number": "IdeaPad 3",
      "display_size": "15.6 inch",
      "ram": "8 GB",
      "rom": "1 TB HDD",
      "price_in_tk": 65000,
      "image": "https://computermania-bd.b-cdn.net/wp-content/uploads/Lenovo-IdeaPad-3-2-1.jpg",
      "color": "Platinum Gray",
      "discount": false,
      "discount_price": 65000
    },
    {
      "brand": "Lenovo",
      "model_number": "Yoga Slim 7i",
      "display_size": "14 inch",
      "ram": "16 GB",
      "rom": "512 GB SSD",
      "price_in_tk": 95000,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJsmBDFSQ7uf8kpBDuKW-sA2L2vGCHi5OEUw&s",
      "color": "Slate Gray",
      "discount": true,
      "discount_price": 85500
    },
    {
      "brand": "Lenovo",
      "model_number": "ThinkPad X1 Carbon",
      "display_size": "14 inch",
      "ram": "16 GB",
      "rom": "1 TB SSD",
      "price_in_tk": 170000,
      "image": "https://ayota.com.bd/cdn/shop/files/LenovoX1CarbonUsed_1024x.png?v=1714040175",
      "color": "Black",
      "discount": false,
      "discount_price": 170000
    },
    {
      "brand": "HP",
      "model_number": "Pavilion 15",
      "display_size": "15.6 inch",
      "ram": "8 GB",
      "rom": "512 GB SSD",
      "price_in_tk": 70000,
      "image": "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c07961107.png",
      "color": "Silver",
      "discount": true,
      "discount_price": 63000
    },
    {
      "brand": "HP",
      "model_number": "Spectre x360",
      "display_size": "13.3 inch",
      "ram": "16 GB",
      "rom": "1 TB SSD",
      "price_in_tk": 130000,
      "image": "https://i.ytimg.com/vi/v_Po_TROcac/sddefault.jpg",
      "color": "Nightfall Black",
      "discount": false,
      "discount_price": 130000
    },
    {
      "brand": "HP",
      "model_number": "Envy 14",
      "display_size": "14 inch",
      "ram": "16 GB",
      "rom": "512 GB SSD",
      "price_in_tk": 110000,
      "image": "https://orangeit.com.bd/wp-content/uploads/2024/04/HP-ENVY-X360-14-es0013dx-2.jpg",
      "color": "Silver",
      "discount": true,
      "discount_price": 99000
    },
    {
      "brand": "Asus",
      "model_number": "ZenBook 14",
      "display_size": "14 inch",
      "ram": "16 GB",
      "rom": "512 GB SSD",
      "price_in_tk": 95000,
      "image": "https://computermania-bd.b-cdn.net/wp-content/uploads/ASUS-Zenbook-14-OLED-Q415MA-Ultrabook-Laptop-4.jpg",
      "color": "Pine Gray",
      "discount": false,
      "discount_price": 95000
    },
    {
      "brand": "Asus",
      "model_number": "ROG Zephyrus G14",
      "display_size": "14 inch",
      "ram": "16 GB",
      "rom": "1 TB SSD",
      "price_in_tk": 140000,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnEDGFoB2nWlvB6IFMhlWYawTN-VIeAr2z5Q&s",
      "color": "Eclipse Gray",
      "discount": true,
      "discount_price": 126000
    },
    {
      "brand": "Asus",
      "model_number": "VivoBook 15",
      "display_size": "15.6 inch",
      "ram": "8 GB",
      "rom": "512 GB SSD",
      "price_in_tk": 65000,
      "image": "https://computermania-bd.b-cdn.net/wp-content/uploads/ASUS-Vivobook-9-6.jpg",
      "color": "Slate Gray",
      "discount": false,
      "discount_price": 65000
    },
    {
      "brand": "Dell",
      "model_number": "Inspiron 15",
      "display_size": "15.6 inch",
      "ram": "8 GB",
      "rom": "512 GB SSD",
      "price_in_tk": 75000,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIoc4XsCeo-W-7zG4Khj_8bemNIU1YkeMK2A&s",
      "color": "Silver",
      "discount": true,
      "discount_price": 67500
    },
    {
      "brand": "Dell",
      "model_number": "XPS 13",
      "display_size": "13.4 inch",
      "ram": "16 GB",
      "rom": "1 TB SSD",
      "price_in_tk": 150000,
      "image": "https://www.custommacbd.com/cdn/shop/products/93003_51db9314-18f6-4d5d-a397-79e7735859df.jpg?v=1613634807",
      "color": "Platinum Silver",
      "discount": false,
      "discount_price": 150000
    },
    {
      "brand": "Dell",
      "model_number": "G5 15",
      "display_size": "15.6 inch",
      "ram": "16 GB",
      "rom": "512 GB SSD",
      "price_in_tk": 120000,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpz5IPI6aey8HDhuHrQWMSmyeX8YruUH_AtA&s",
      "color": "Black",
      "discount": true,
      "discount_price": 108000
    },
    {
      "brand": "Apple",
      "model_number": "MacBook Air M2",
      "display_size": "13.6 inch",
      "ram": "8 GB",
      "rom": "256 GB SSD",
      "price_in_tk": 115000,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4a4B4zdQy3M0jQ6m2RtqFSmXRu8vCWCgt3g&s",
      "color": "Gold",
      "discount": false,
      "discount_price": 115000
    },
    {
      "brand": "Lenovo",
      "model_number": "Legion 5",
      "display_size": "15.6 inch",
      "ram": "16 GB",
      "rom": "512 GB SSD",
      "price_in_tk": 105000,
      "image": "https://computermania-bd.b-cdn.net/wp-content/uploads/Lenovo-1-1.jpg",
      "color": "Phantom Blue",
      "discount": true,
      "discount_price": 94500
    },
    {
      "brand": "HP",
      "model_number": "Omen 15",
      "display_size": "15.6 inch",
      "ram": "16 GB",
      "rom": "1 TB SSD",
      "price_in_tk": 135000,
      "image": "https://neton.com.bd/wp-content/uploads/2023/10/HP_OMEN_15-removebg-preview.webp",
      "color": "Shadow Black",
      "discount": false,
      "discount_price": 135000
    },
    {
      "brand": "Asus",
      "model_number": "TUF Gaming A15",
      "display_size": "15.6 inch",
      "ram": "16 GB",
      "rom": "512 GB SSD",
      "price_in_tk": 95000,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgos56RYTNbJTqxZYLlPb-7-rCf-g1n3pm7w&s",
      "color": "Fortress Gray",
      "discount": true,
      "discount_price": 85500
    },
    {
      "brand": "Dell",
      "model_number": "Alienware m15",
      "display_size": "15.6 inch",
      "ram": "32 GB",
      "rom": "1 TB SSD",
      "price_in_tk": 200000,
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1jezrlje8i0kil4T3ulHBac09jLad_EaXXA&s",
      "color": "Lunar Light",
      "discount": false,
      "discount_price": 200000
    }
  ]
  
export default data  